#!/usr/bin/env bash

set -euo pipefail

APP_DIR="/var/www/midas"
SERVICE_NAME="midas"
SERVICE_USER="www-data"
DOMAIN="example.com"
ADDITIONAL_DOMAINS=""
BACKEND_PORT=8000
WORKERS=2
SOURCE_DIR="$(pwd)"
SKIP_SYSTEMD=0
SKIP_NGINX=1
ASSUME_YES=0

usage() {
  cat <<'EOF'
Usage: sudo ./deploy.sh [options]

Options:
  --app-dir PATH        Target directory on the server (default: /var/www/midas)
  --service-name NAME   Systemd service name (default: midas)
  --service-user USER   Linux user to run the app (default: www-data)
  --domain NAME         Public domain for Nginx server_name (default: example.com)
  --backend-port PORT   Internal backend port (default: 8000)
  --workers N           Uvicorn worker count (default: 2)
  --source PATH         Source repo to deploy (default: current directory)
  --skip-systemd        Only sync/build without touching systemd
  --skip-nginx          Explicitly skip Nginx configuration (default)
  --configure-nginx     Enable Nginx configuration
  --yes                 Assume "yes" for prompts
  -h, --help            Show this help
EOF
}

configure_env_file() {
  local env_path="${APP_DIR}/.env"

  if [[ -f "${env_path}" ]]; then
    log ".env already present at ${env_path}"
    return
  fi

  log "Creating .env at ${env_path}"

  local default_api_host="0.0.0.0"
  local default_api_port="${BACKEND_PORT}"
  local default_db_url="sqlite+aiosqlite:///./midas.db"
  local default_cors="http://${DOMAIN},http://localhost:3000,http://localhost:5173"
  local generated_secret
  generated_secret=$(python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(32))
PY
  )

  local api_host_input api_port_input secret_key_input db_url_input cors_input

  if [[ $ASSUME_YES -eq 1 ]]; then
    api_host_input="${default_api_host}"
    api_port_input="${default_api_port}"
    secret_key_input="${generated_secret}"
    db_url_input="${default_db_url}"
    cors_input="${default_cors}"
  else
    read -r -p "API host [${default_api_host}]: " api_host_input
    read -r -p "API port [${default_api_port}]: " api_port_input
    read -r -p "Database URL [${default_db_url}]: " db_url_input
    read -r -p "CORS origins (comma separated) [${default_cors}]: " cors_input
    read -r -p "Secret key (leave blank to auto-generate): " secret_key_input
  fi

  api_host_input=${api_host_input:-$default_api_host}
  api_port_input=${api_port_input:-$default_api_port}
  db_url_input=${db_url_input:-$default_db_url}
  cors_input=${cors_input:-$default_cors}
  secret_key_input=${secret_key_input:-$generated_secret}

  cat <<EOF >"${env_path}"
# Generated by deploy.sh
API_HOST=${api_host_input}
API_PORT=${api_port_input}
SECRET_KEY=${secret_key_input}

# LLM API Keys (fill in as needed)
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
GOOGLE_API_KEY=
OLLAMA_BASE_URL=http://localhost:11434

# Database
DATABASE_URL=${db_url_input}

# CORS
CORS_ORIGINS=${cors_input}
EOF

  chmod 640 "${env_path}"
  log ".env created. Update API keys before going live."
}

prompt_domains_and_ports() {
  if [[ $ASSUME_YES -eq 1 ]]; then
    return
  fi

  read -r -p "Primary domain (for server_name) [${DOMAIN}]: " input
  if [[ -n ${input} ]]; then
    DOMAIN=${input}
  fi

  read -r -p "Additional domains (space separated, optional): " input
  if [[ -n ${input} ]]; then
    ADDITIONAL_DOMAINS=${input}
  fi

  read -r -p "Backend port [${BACKEND_PORT}]: " input
  if [[ -n ${input} ]]; then
    BACKEND_PORT=${input}
  fi
}

log() {
  echo -e "\033[1;34m[+]\033[0m $*"
}

require_root() {
  if [[ $EUID -ne 0 ]]; then
    echo "Run this script as root (sudo)."
    exit 1
  fi
}

confirm() {
  local prompt=$1
  if [[ $ASSUME_YES -eq 1 ]]; then
    return 0
  fi
  read -r -p "$prompt [y/N]: " response
  [[ $response =~ ^[Yy]$ ]]
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --app-dir)
        APP_DIR="$2"; shift 2 ;;
      --service-name)
        SERVICE_NAME="$2"; shift 2 ;;
      --service-user)
        SERVICE_USER="$2"; shift 2 ;;
      --domain)
        DOMAIN="$2"; shift 2 ;;
      --backend-port)
        BACKEND_PORT="$2"; shift 2 ;;
      --workers)
        WORKERS="$2"; shift 2 ;;
      --source)
        SOURCE_DIR="$2"; shift 2 ;;
      --skip-systemd)
        SKIP_SYSTEMD=1; shift ;;
      --skip-nginx)
        SKIP_NGINX=1; shift ;;
      --configure-nginx)
        SKIP_NGINX=0; shift ;;
      --yes)
        ASSUME_YES=1; shift ;;
      -h|--help)
        usage; exit 0 ;;
      *)
        echo "Unknown option: $1"; usage; exit 1 ;;
    esac
  done
}

install_dependencies() {
  log "Installing OS packages..."
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y python3 python3-venv python3-pip nodejs npm nginx git curl rsync

  if command -v node >/dev/null 2>&1; then
    local major
    major=$(node -v | sed 's/^v//' | cut -d. -f1)
    if (( major < 18 )); then
      log "Upgrading Node.js to 18.x"
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
    fi
  else
    log "Installing Node.js 18.x"
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    apt-get install -y nodejs
  fi
}

sync_source() {
  log "Syncing source to $APP_DIR"
  mkdir -p "$APP_DIR"
  rsync -a --delete --exclude ".git" --exclude "venv" "$SOURCE_DIR/" "$APP_DIR/"
}

setup_python() {
  log "Setting up Python virtual environment"
  python3 -m venv "${APP_DIR}/venv" >/dev/null 2>&1 || true
  # shellcheck disable=SC1091
  source "${APP_DIR}/venv/bin/activate"
  pip install --upgrade pip wheel
  pip install -r "${APP_DIR}/requirements.txt"
  deactivate
}

build_frontend() {
  log "Installing frontend dependencies and building"
  pushd "$APP_DIR/frontend" >/dev/null
  if [[ -f package-lock.json ]]; then
    npm ci --no-progress
  else
    npm install --no-progress
  fi
  npm run build
  popd >/dev/null
}

configure_systemd() {
  if [[ $SKIP_SYSTEMD -eq 1 ]]; then
    return
  fi

  log "Writing systemd unit /etc/systemd/system/${SERVICE_NAME}.service"
  cat <<EOF >/etc/systemd/system/${SERVICE_NAME}.service
[Unit]
Description=MIDAS API (${SERVICE_NAME})
After=network.target

[Service]
Type=simple
User=${SERVICE_USER}
WorkingDirectory=${APP_DIR}
Environment="PATH=${APP_DIR}/venv/bin"
EnvironmentFile=-${APP_DIR}/.env
ExecStart=${APP_DIR}/venv/bin/uvicorn backend.main:app --host 127.0.0.1 --port ${BACKEND_PORT} --workers ${WORKERS}
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable --now "${SERVICE_NAME}.service"
  systemctl status "${SERVICE_NAME}.service" --no-pager
}

configure_nginx() {
  if [[ $SKIP_NGINX -eq 1 ]]; then
    return
  fi

  local SERVER_NAMES=${DOMAIN}
  if [[ -n ${ADDITIONAL_DOMAINS} ]]; then
    SERVER_NAMES="${SERVER_NAMES} ${ADDITIONAL_DOMAINS}"
  fi

  log "Configuring Nginx vhost /etc/nginx/sites-available/${SERVICE_NAME}.conf"
  cat <<EOF >/etc/nginx/sites-available/${SERVICE_NAME}.conf
server {
    listen 80;
    server_name ${SERVER_NAMES};

    root ${APP_DIR}/frontend/dist;
    index index.html;

    location / {
        try_files \$uri \$uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:${BACKEND_PORT}/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
}
EOF

  ln -sf "/etc/nginx/sites-available/${SERVICE_NAME}.conf" \
    "/etc/nginx/sites-enabled/${SERVICE_NAME}.conf"
  nginx -t
  systemctl reload nginx
}

summary() {
  cat <<EOF

Deployment complete.
- App directory: ${APP_DIR}
- Systemd unit: ${SERVICE_NAME}.service (skip with --skip-systemd)
- Nginx config: /etc/nginx/sites-available/${SERVICE_NAME}.conf (skip with --skip-nginx)

Remember to edit ${APP_DIR}/.env with real API keys and restart the service:
  sudo systemctl restart ${SERVICE_NAME}

Point your DNS A record at this server so ${DOMAIN} resolves correctly.
EOF
}

main() {
  parse_args "$@"
  prompt_domains_and_ports
  require_root
  install_dependencies
  sync_source
  configure_env_file
  setup_python
  build_frontend
  configure_systemd
  configure_nginx
  summary
}

main "$@"
